---
docker_redhat_package: 
    - docker-ce
    - docker-ce-cli
    - docker-compose-plugin
docker_debian_package:
  - docker-ce
  - docker-ce-ci
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
